name: deploy_frontend
# Deploys when push is made from frontend folder

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login with Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage ($web)
        uses: azure/CLI@v2
        with:
          inlineScript: |
            set -euo pipefail

            az storage blob upload-batch \
              --account-name azureresumestorage \
              --destination '$web' \
              --source frontend/ \
              --auth-mode login \
              --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            set -euo pipefail

            az cdn endpoint purge \
              --content-paths "/*" \
              --profile-name "CloudResumeChallengeGPS" \
              --name "gpsazuresume" \
              --resource-group "cloud-resume-challenge-rg"

      - name: Logout
        if: always()
        run: az logout
